version: "2.1"

services:
  postgres:
    image: postgres
    ports:
      - "${PG_PORT:-5432}:5432"  # for debugging
    volumes:
      - iloop-upload:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"  # for debugging
  iworker:
    image: iloop:latest
    command: python3 worker.py -A iloop.extensions.celery worker
    links:
      - postgres
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_PORT_5432_TCP_ADDR=postgres:5432
      - REDIS_PORT_6379_TCP_ADDR=redis:6379
  web:
    image: iloop:latest
    command: python3 manage.py runserver
    ports:
      - "${API_PORT:-80}:80"
    links:
      - postgres
      - redis
    environment:
      - API_PREFIX=/api
      - PYTHONUNBUFFERED=1
      - POSTGRES_PORT_5432_TCP_ADDR=postgres:5432
      - REDIS_PORT_6379_TCP_ADDR=redis:6379
  upload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${UPLOAD_PORT:-7000}:7000"
    volumes:
      - ./:/source
    links:
      - web
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ILOOP_TOKEN
      - ILOOP_API=web:80/api

volumes:
  iloop-upload:
    external: true
