version: "3.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/dd-decaf-cfbf6/upload:${IMAGE_TAG:-latest}
    command: gunicorn -c gunicorn.py upload.app:get_app()
    ports:
      - "${UPLOAD_PORT:-8000}:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ILOOP_TOKEN
      - ILOOP_API=${ILOOP_API:-http://iloop-backend:80/api}
    networks:
      DD-DeCaF:
        aliases:
          - iloop-to-model

networks:
  DD-DeCaF:
    external: true
