version: "2.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "-w 2 -b 0.0.0.0:7000 -t 150 -k aiohttp.worker.GunicornWebWorker --reload upload.app:app"
    ports:
      - "${UPLOAD_PORT:-7000}:7000"
    volumes:
      - ./:/source
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ILOOP_TOKEN
      - ILOOP_API=${ILOOP_API:-http://iloop-backend:80/api}
    networks:
      iloop:
        aliases:
          - upload-backend

networks:
  iloop:
    external: true
