version: "2.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${UPLOAD_PORT:-7100}:7100"
    volumes:
      - ./:/source
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ILOOP_TOKEN
      - ILOOP_API=${ILOOP_API:-iloop-backend:80/api}
    networks:
      - iloop-net

networks:
  iloop-net:
    external: true
