version: "2.1"

services:
  upload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${UPLOAD_PORT:-7000}:7000"
    volumes:
      - ./:/source
    links:
      - web
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ILOOP_TOKEN
      - ILOOP_API=iloop-backend:80/api
    networks:
      - iloop-net

networks:
  iloop-net:
    external: true
