version: "2.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${UPLOAD_PORT:-7000}:7000"
    volumes:
      - ./:/source
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ILOOP_TOKEN
      - ILOOP_API=${ILOOP_API:-http://iloop-backend:80/api}
    networks:
      iloop:
        aliases:
          - upload-backend

networks:
  iloop:
    external: true
