apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-production
spec:
  selector:
    matchLabels:
      app: upload
      env: production
  replicas: 1
  template:
    metadata:
      labels:
        app: upload
        env: production
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/upload:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ILOOP_API
          value: http://iloop-production/api
        - name: MODEL_API
          value: http://model-production
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: upload-production
              key: SENTRY_DSN
        - name: ILOOP_TOKEN
          valueFrom:
            secretKeyRef:
              name: upload-production
              key: ILOOP_TOKEN
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
