apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-legacy
spec:
  selector:
    matchLabels:
      app: upload
      env: legacy
  replicas: 1
  template:
    metadata:
      labels:
        app: upload
        env: legacy
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/upload:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ILOOP_API
          value: http://iloop-production/api
        - name: MODEL_API
          value: http://model-legacy
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: upload-legacy
              key: SENTRY_DSN
        - name: ILOOP_TOKEN
          valueFrom:
            secretKeyRef:
              name: upload-legacy
              key: ILOOP_TOKEN
        resources:
          requests:
            cpu: "0"
