kind: Service
apiVersion: v1
metadata:
  name: upload-production
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  selector:
    app: upload
    env: production
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 7000

---

kind: Service
apiVersion: v1
metadata:
  name: upload-staging
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  selector:
    app: upload
    env: staging
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 7000
